"use strict";
// chronal install [--update]: the game the sim and the replay viewer run, a copy in runtime/app (the repos stay
// untouched): the game's three repos in config upstream (cloned when missing; --update: git pull --ff-only first),
// copied without their big static folders (linked) and installed (npm install when a package.json changed), and its
// secretsandconfig generated from the upstream template (keys of this install, the local server's options).
const fs = require("node:fs"),
	path = require("node:path"),
	crypto = require("node:crypto"),
	{ execSync, execFileSync } = require("node:child_process");
const { ROOT, config } = require("./config");

const REPOS = { game: ["adventureland_mongodb", "https://github.com/kaansoral/adventureland_mongodb"], common: ["common_engine", "https://github.com/kaansoral/common_engine"], config: ["adventureland_secretsandconfig", "https://github.com/kaansoral/adventureland_secretsandconfig"] };
const RUNTIME = path.join(ROOT, "runtime"),
	APP = path.join(RUNTIME, "app"),
	SECRETS = path.join(RUNTIME, "secretsandconfig");
const LINKED = ["images", "sounds"]; // served as static files only
const SKIP = [".git", "node_modules", "node/node_modules", "package-lock.json", "node/package-lock.json", "common", "secretsandconfig", "tauri", ...LINKED];

const sh = (cmd, opts = {}) => execSync(cmd, { stdio: "inherit", ...opts });
const hash = (files) => {
	const h = crypto.createHash("sha1");
	for (const f of files) h.update(fs.existsSync(f) ? fs.readFileSync(f) : "");
	return h.digest("hex");
};

// this install's secrets (made once): every process of the game must agree on them
function keys() {
	const f = path.join(RUNTIME, "keys.json");
	if (!fs.existsSync(f)) {
		const rk = (n) => crypto.randomBytes(n).toString("hex");
		fs.mkdirSync(RUNTIME, { recursive: true });
		fs.writeFileSync(f, JSON.stringify({ ACCESS_MASTER: rk(20), BOT_MASTER: rk(20), SERVER_MASTER: rk(16) }, null, 2));
	}
	return JSON.parse(fs.readFileSync(f, "utf8"));
}

// keys.js and options.js over the upstream template's: a local game server US I (the sim boots it; no database is
// used: the sim and the viewer give the game an in-memory one)
function writeSecrets(template) {
	const k = keys();
	fs.mkdirSync(SECRETS, { recursive: true });
	fs.writeFileSync(
		path.join(SECRETS, "keys.js"),
		`// generated by chronal install (lib/install.js) - edits are overwritten
module.exports = Object.assign(require(${JSON.stringify(path.join(template, "keys.js"))}), {
	mongodb_uri: "mongodb://127.0.0.1:27017/?directConnection=true",
	mongodb_name: "adventureland",
	mongodb_config: {},
	ACCESS_MASTER: ${JSON.stringify(k.ACCESS_MASTER)},
	BOT_MASTER: ${JSON.stringify(k.BOT_MASTER)},
	SERVER_MASTER: ${JSON.stringify(k.SERVER_MASTER)},
});
`,
	);
	fs.writeFileSync(
		path.join(SECRETS, "options.js"),
		`// generated by chronal install (lib/install.js) - edits are overwritten
const options = require(${JSON.stringify(path.join(template, "options.js"))});
module.exports = Object.assign({}, options, {
	base_url: "http://localhost:8090",
	port: 8090,
	Dev: false,
	Local: true,
	Prod: false,
	Staging: false,
	unsecure_admin: false,
	secure: false,
	discord_chat_channel: "",
	servers: {
		local: {
			region: "US",
			name: "I",
			path: "/socket.io/",
			msgpack_path: "/socket.io-msgpack/",
			api_path: "/server.api/",
			local_ip: "127.0.0.1",
			local_port: 7192,
			address: "localhost:7192",
			machine: "local",
		},
	},
});
`,
	);
}

/** @param {string[]} args ["--update"]: git pull the repos first. -> { game, common, config }: each repo's commit */
function install(args = []) {
	const upstream = config().upstream,
		up = Object.fromEntries(Object.entries(REPOS).map(([k, [dir]]) => [k, path.join(upstream, dir)]));
	for (const [k, d] of Object.entries(up)) {
		if (!fs.existsSync(d)) sh(`git clone ${REPOS[k][1]} ${JSON.stringify(d)}`);
		else if (args.includes("--update")) execFileSync("git", ["-C", d, "pull", "--ff-only"], { stdio: "inherit" });
	}
	// copy the game, keeping what npm installed
	const keep = path.join(RUNTIME, ".keep"),
		kept = ["node_modules", "node/node_modules", "package-lock.json", "node/package-lock.json", ".deps"];
	fs.rmSync(keep, { recursive: true, force: true });
	fs.mkdirSync(keep, { recursive: true });
	for (const k of kept) if (fs.existsSync(path.join(APP, k))) fs.renameSync(path.join(APP, k), path.join(keep, k.replace("/", "__")));
	fs.rmSync(APP, { recursive: true, force: true });
	fs.mkdirSync(APP, { recursive: true });
	sh(`tar -C ${JSON.stringify(up.game)} ${SKIP.map((s) => `--exclude=./${s}`).join(" ")} -cf - . | tar -C ${JSON.stringify(APP)} -xf -`, { shell: "/bin/bash" });
	for (const k of kept) if (fs.existsSync(path.join(keep, k.replace("/", "__")))) fs.renameSync(path.join(keep, k.replace("/", "__")), path.join(APP, k));
	fs.rmSync(keep, { recursive: true, force: true });
	for (const d of LINKED) fs.symlinkSync(path.join(up.game, d), path.join(APP, d));
	fs.symlinkSync(up.common, path.join(APP, "common"));
	fs.symlinkSync(SECRETS, path.join(APP, "secretsandconfig"));
	writeSecrets(up.config);
	// npm install only when a package.json changed (argon2 and @mongodb-js/zstd are declared but unused: no install scripts)
	const want = hash([path.join(APP, "package.json"), path.join(APP, "node/package.json")]),
		stamp = path.join(APP, ".deps");
	if (want !== (fs.existsSync(stamp) ? fs.readFileSync(stamp, "utf8") : "") || !fs.existsSync(path.join(APP, "node_modules")) || !fs.existsSync(path.join(APP, "node/node_modules"))) {
		sh("npm install --no-audit --no-fund --ignore-scripts", { cwd: APP });
		sh("npm install --no-audit --no-fund", { cwd: path.join(APP, "node") });
		fs.writeFileSync(stamp, want);
	}
	return Object.fromEntries(Object.entries(up).map(([k, d]) => [k, execFileSync("git", ["-C", d, "rev-parse", "--short", "HEAD"], { encoding: "utf8" }).trim()]));
}

module.exports = { install };
