"use strict";
// chronal install [--update | --latest | --check]: the game the sim and the replay viewer run, a copy in runtime/app:
// the game's three repos in config upstream (cloned when missing), each checked out (detached) at the commit this
// chronal is tested with (upstream.json; --update: fetched first; --latest: upstream's newest, untested), copied without
// their big static folders (linked) and installed (npm install when a package.json changed), and its secretsandconfig
// generated from the upstream template (keys of this install, the local server's options). runtime/installed.json says
// what is installed; chronal run and the dashboard warn when it isn't the pin (gameCheck). --check: the pinned, the
// installed and upstream's newest commits, and how far upstream is ahead (it fetches; it installs nothing).
const fs = require("node:fs"),
	path = require("node:path"),
	crypto = require("node:crypto"),
	{ execSync, execFileSync } = require("node:child_process");
const { ROOT, config } = require("./config");

// the game's repos and the commits this chronal is tested with: { game, common, config: { dir, url, commit } }
const PIN_FILE = path.join(ROOT, "upstream.json");
const pins = () => JSON.parse(fs.readFileSync(PIN_FILE, "utf8"));
const RUNTIME = path.join(ROOT, "runtime"),
	APP = path.join(RUNTIME, "app"),
	SECRETS = path.join(RUNTIME, "secretsandconfig"),
	INSTALLED = path.join(RUNTIME, "installed.json");
const git = (d, ...a) => execFileSync("git", ["-C", d, ...a], { encoding: "utf8", stdio: ["ignore", "pipe", "pipe"] }).trim();
const short = (c) => (c ? c.slice(0, 8) : null);
const LINKED = ["images", "sounds"]; // served as static files only
const SKIP = [".git", "node_modules", "node/node_modules", "package-lock.json", "node/package-lock.json", "common", "secretsandconfig", "tauri", ...LINKED];

const sh = (cmd, opts = {}) => execSync(cmd, { stdio: "inherit", ...opts });
const hash = (files) => {
	const h = crypto.createHash("sha1");
	for (const f of files) h.update(fs.existsSync(f) ? fs.readFileSync(f) : "");
	return h.digest("hex");
};

// this install's secrets (made once): every process of the game must agree on them
function keys() {
	const f = path.join(RUNTIME, "keys.json");
	if (!fs.existsSync(f)) {
		const rk = (n) => crypto.randomBytes(n).toString("hex");
		fs.mkdirSync(RUNTIME, { recursive: true });
		fs.writeFileSync(f, JSON.stringify({ ACCESS_MASTER: rk(20), BOT_MASTER: rk(20), SERVER_MASTER: rk(16) }, null, 2));
	}
	return JSON.parse(fs.readFileSync(f, "utf8"));
}

// keys.js and options.js over the upstream template's: a local game server US I (the sim boots it; no database is
// used: the sim and the viewer give the game an in-memory one)
function writeSecrets(template) {
	const k = keys();
	fs.mkdirSync(SECRETS, { recursive: true });
	fs.writeFileSync(
		path.join(SECRETS, "keys.js"),
		`// generated by chronal install (lib/install.js) - edits are overwritten
module.exports = Object.assign(require(${JSON.stringify(path.join(template, "keys.js"))}), {
	mongodb_uri: "mongodb://127.0.0.1:27017/?directConnection=true",
	mongodb_name: "adventureland",
	mongodb_config: {},
	ACCESS_MASTER: ${JSON.stringify(k.ACCESS_MASTER)},
	BOT_MASTER: ${JSON.stringify(k.BOT_MASTER)},
	SERVER_MASTER: ${JSON.stringify(k.SERVER_MASTER)},
});
`,
	);
	fs.writeFileSync(
		path.join(SECRETS, "options.js"),
		`// generated by chronal install (lib/install.js) - edits are overwritten
const options = require(${JSON.stringify(path.join(template, "options.js"))});
module.exports = Object.assign({}, options, {
	base_url: "http://localhost:8090",
	port: 8090,
	Dev: false,
	Local: true,
	Prod: false,
	Staging: false,
	unsecure_admin: false,
	secure: false,
	discord_chat_channel: "",
	servers: {
		local: {
			region: "US",
			name: "I",
			path: "/socket.io/",
			msgpack_path: "/socket.io-msgpack/",
			api_path: "/server.api/",
			local_ip: "127.0.0.1",
			local_port: 7192,
			address: "localhost:7192",
			machine: "local",
		},
	},
});
`,
	);
}

/** The game's repos in upstream (cloned when missing), each checked out (detached) at its pin, or upstream's newest
 * (latest); fetched first with update or latest, or when the commit is missing. -> { game, common, config }: their
 * directories; target: the commits */
function checkout(P, upstream, { latest = false, update = false } = {}) {
	const up = {},
		target = {};
	for (const [k, r] of Object.entries(P)) {
		const d = (up[k] = path.join(upstream, r.dir));
		if (!fs.existsSync(d)) execFileSync("git", ["clone", "-q", r.url, d], { stdio: "inherit" });
		const has = (c) => { try { return git(d, "cat-file", "-t", c + "^{commit}") === "commit"; } catch (e) { return false; } };
		if (latest || update || !has(r.commit)) execFileSync("git", ["-C", d, "fetch", "-q", "origin"], { stdio: "inherit" });
		target[k] = latest ? git(d, "rev-parse", "origin/HEAD") : r.commit;
		if (!has(target[k])) throw new Error(`${r.dir}: no commit ${target[k]} (upstream.json) in ${r.url}`);
		if (git(d, "rev-parse", "HEAD") !== target[k]) execFileSync("git", ["-C", d, "checkout", "-q", "--detach", target[k]], { stdio: "inherit" });
	}
	return { up, target };
}

/** @param {string[]} args "--update": fetch the repos first; "--latest": upstream's newest commits instead of the pins.
 * -> { game, common, config }: each repo's commit (8), pinned: whether they are the pins */
function install(args = []) {
	const P = pins(),
		latest = args.includes("--latest"),
		{ up, target } = checkout(P, config().upstream, { latest, update: args.includes("--update") });
	if (latest) console.warn(`chronal install --latest: the game's newest commits (${Object.entries(target).map(([k, c]) => k + " " + short(c)).join(", ")}), not the ones this chronal is tested with: runs may fail or differ`);
	// copy the game, keeping what npm installed
	const keep = path.join(RUNTIME, ".keep"),
		kept = ["node_modules", "node/node_modules", "package-lock.json", "node/package-lock.json", ".deps"];
	fs.rmSync(keep, { recursive: true, force: true });
	fs.mkdirSync(keep, { recursive: true });
	for (const k of kept) if (fs.existsSync(path.join(APP, k))) fs.renameSync(path.join(APP, k), path.join(keep, k.replace("/", "__")));
	fs.rmSync(APP, { recursive: true, force: true });
	fs.mkdirSync(APP, { recursive: true });
	sh(`tar -C ${JSON.stringify(up.game)} ${SKIP.map((s) => `--exclude=./${s}`).join(" ")} -cf - . | tar -C ${JSON.stringify(APP)} -xf -`, { shell: "/bin/bash" });
	for (const k of kept) if (fs.existsSync(path.join(keep, k.replace("/", "__")))) fs.renameSync(path.join(keep, k.replace("/", "__")), path.join(APP, k));
	fs.rmSync(keep, { recursive: true, force: true });
	for (const d of LINKED) fs.symlinkSync(path.join(up.game, d), path.join(APP, d));
	fs.symlinkSync(up.common, path.join(APP, "common"));
	fs.symlinkSync(SECRETS, path.join(APP, "secretsandconfig"));
	writeSecrets(up.config);
	// npm install only when a package.json changed (argon2 and @mongodb-js/zstd are declared but unused: no install scripts)
	const want = hash([path.join(APP, "package.json"), path.join(APP, "node/package.json")]),
		stamp = path.join(APP, ".deps");
	if (want !== (fs.existsSync(stamp) ? fs.readFileSync(stamp, "utf8") : "") || !fs.existsSync(path.join(APP, "node_modules")) || !fs.existsSync(path.join(APP, "node/node_modules"))) {
		sh("npm install --no-audit --no-fund --ignore-scripts", { cwd: APP });
		sh("npm install --no-audit --no-fund", { cwd: path.join(APP, "node") });
		fs.writeFileSync(stamp, want);
	}
	const got = Object.fromEntries(Object.keys(up).map((k) => [k, git(up[k], "rev-parse", "HEAD")])),
		pinned = Object.keys(P).every((k) => got[k] === P[k].commit);
	fs.writeFileSync(INSTALLED, JSON.stringify({ ...got, pinned, at: new Date().toISOString() }, null, 2) + "\n");
	return { ...Object.fromEntries(Object.entries(got).map(([k, c]) => [k, short(c)])), pinned };
}

/** What runtime/app holds: runtime/installed.json { game, common, config, pinned, at } | null (an install from before
 * chronal 0.8.0, or none) */
function installed(file = INSTALLED) {
	try {
		return JSON.parse(fs.readFileSync(file, "utf8"));
	} catch (e) {
		return null;
	}
}

/** The game the sim runs against the pin: { ok, game (8, null: unknown), pinned (8), text: a warning | null }. A game
 * that isn't runtime/app (config al_root elsewhere) is the user's own: ok, game null. */
function gameCheck(alRoot = config().al_root, { P = pins(), app = APP, file = INSTALLED } = {}) {
	const pinned = short(P.game.commit);
	if (path.resolve(alRoot) !== path.resolve(app)) return { ok: true, game: null, pinned, text: null };
	const i = installed(file);
	if (!i) return { ok: false, game: null, pinned, text: `the game in runtime/app was installed before chronal recorded what it installs: run chronal install (the game this chronal is tested with: ${pinned})` };
	const off = Object.keys(P).filter((k) => i[k] !== P[k].commit);
	if (!off.length) return { ok: true, game: short(i.game), pinned, text: null };
	return { ok: false, game: short(i.game), pinned, text: `the game installed (${off.map((k) => k + " " + short(i[k])).join(", ")}) isn't the one this chronal is tested with (${off.map((k) => k + " " + short(P[k].commit)).join(", ")}): run chronal install` };
}

/** chronal install --check: per repo the pinned, installed and upstream's newest commits, and how far upstream is ahead
 * of the pin (fetches the repos) */
function check({ P = pins(), upstream = config().upstream, file = INSTALLED } = {}) {
	const i = installed(file) || {},
		rows = [];
	for (const [k, r] of Object.entries(P)) {
		const d = path.join(upstream, r.dir);
		if (!fs.existsSync(d)) {
			rows.push({ repo: r.dir, pinned: short(r.commit), installed: short(i[k]), upstream: "?", ahead: "? (not cloned: chronal install)" });
			continue;
		}
		git(d, "fetch", "-q", "origin");
		const head = git(d, "rev-parse", "origin/HEAD");
		let ahead;
		try {
			ahead = Number(git(d, "rev-list", "--count", r.commit + ".." + head));
		} catch (e) {
			ahead = "?";
		}
		rows.push({ repo: r.dir, pinned: short(r.commit), installed: short(i[k]), upstream: short(head), ahead });
	}
	return rows;
}

function cli(args) {
	try {
		if (args.includes("--check")) {
			const rows = check();
			console.table(rows);
			const g = gameCheck();
			if (g.text) console.warn("warning: " + g.text);
			const behind = rows.filter((r) => typeof r.ahead === "number" && r.ahead > 0);
			console.log(behind.length ? `upstream is ahead of the pin: ${behind.map((r) => r.repo + " by " + r.ahead + " commit" + (r.ahead === 1 ? "" : "s")).join(", ")} (chronal install --latest tries the newest; a chronal release moves the pin)` : "upstream is at the pin");
			return;
		}
		console.log("installed:", JSON.stringify(install(args)));
		// its game data for the dashboard (cache/G-<version>-<game>.json)
		execFileSync(process.execPath, [path.join(ROOT, "chronal.js"), "g-data"], { stdio: "inherit" });
	} catch (e) {
		console.error("chronal install: " + e.message);
		process.exit(1);
	}
}

module.exports = { install, checkout, installed, gameCheck, check, cli, PIN_FILE };
